name: dynamic_island_watermark
description: "Show a watermark behind the dynamic island on supported iPhone models"
version: 1.0.0
repository: https://github.com/ueman/dart-packages
issue_tracker: https://github.com/ueman/dart-packages/issues

topics:
  - dynamic-island
  - watermark
  - iphone

environment:
  sdk: ^3.6.0
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter
  device_info_plus: ^11.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter: